/*****************************************************************************
File name:   error.h
Description: 用于存放工程代码不断增高的所有的错误定义
Author:      Zako
Version:     1.0
Date:        2022.06.09
History:
20220609     初始化格式文档
****************************************************************************/
#ifndef COMMON_ERROR_H
#define COMMON_ERROR_H
#include <stdint.h>

//----------------------------------规范化错误定义-----------------------------------------
//返回错误码，代码膨胀厉害，较多的魔鬼数字难以理解处理
//所有枚举定义变量只增加不删除，如果不用，则修改名称后置空保留原位置，防止影响其他值
enum ErrorCode {
    RET_SUCCESS = 0,
    ERR_GENERIC = INT32_MIN,
    //----发票相关错误代码-[1w,2w),此部分定义值外部使用且存在于错误代码表，不可更改
    DF_TAX_ERR_CODE_COMMON = -10000,
    DF_TAX_ERR_CODE_TER_SYSTEM_ERROR = -10301,             //终端系统错误
    DF_TAX_ERR_CODE_COMMAND_UNSUPPORTED = -10302,          //命令字不支持
    DF_TAX_ERR_CODE_SYSTEM_MEM_INSUFFICIENT = -10303,      //系统内存不足
    DF_TAX_ERR_CODE_DATA_PARSING_FAILED = -10304,          // json解析失败
    DF_TAX_ERR_CODE_EXCEED_KP_END_DATE = -10305,           //超过开票截止日期
    DF_TAX_ERR_CODE_EXCEED_SINGLE_LIMIT = -10306,          //超过单张发票开票限额
    DF_TAX_ERR_CODE_EXCEED_OFFLINE_LIMIT = -10307,         //超过离线限额
    DF_TAX_ERR_CODE_UNSUPPORT_INV_TYPE = -10308,           //不支持该发票类型
    DF_TAX_ERR_CODE_INV_DATA_ANALYSIS_ERR = -10309,        //发票数据解析失败
    DF_TAX_ERR_CODE_TAX_RATE_UNSUPPORTED = -10310,         //授权税率不支持
    DF_TAX_ERR_CODE_HAVE_NO_INVOICE = -10311,              //没有可用发票
    DF_TAX_ERR_CODE_SYSTEM_TIME_ERROR = -10312,            //当前终端系统时间错误
    DF_TAX_ERR_CODE_INV_DATA_TOO_LARGE = -10313,           //发票数量过大
    DF_TAX_ERR_CODE_PLATE_IN_USED = -10314,                //税盘正在被使用
    DF_TAX_ERR_CODE_INV_DATA_DISACCORD = -10315,           //开票数据与税盘信息不一致
    DF_TAX_ERR_CODE_PLATE_OPER_FAILED = -10316,            //税盘操作失败
    DF_TAX_ERR_CODE_PLATE_CERT_PASSWD_ERR = -10317,        //证书口令错误
    DF_TAX_ERR_CODE_EXCEED_OFFLINE_LIMIT_TIME = -10318,    //超过离线时长
    DF_TAX_ERR_CODE_PLATE_NON_EXISTENT = -10319,           //税盘不在该终端上
    DF_TAX_ERR_CODE_MONTH_HAVE_NO_INVPICE = -10320,        //当前要查询无发票
    DF_TAX_ERR_CODE_USE_ILL_CHAR_OR_UTF8 = -10321,         //使用了非法字符或utf8编码
    DF_TAX_ERR_CODE_CAN_NOT_USE_IOZSV = -10322,            //税号中不能使用IOZSV非法字符
    DF_TAX_ERR_CODE_INV_SERIAL_NUMBER_UNEXIST = -10323,    //发票流水号不存在
    DF_TAX_ERR_CODE_INV_SERIAL_NUMBER_BEEN_USED = -10324,  //该发票流水号已经开具过了
    DF_TAX_ERR_CODE_CONNECT_MYSQL_ERROR = -10325,          //连接数据库失败
    DF_TAX_ERR_CODE_FPQQLSH_IS_INUSING = -10326,           //当前流水号正在开票中
    DF_TAX_ERR_CODE_USB_PORT_NOT_AUTH = -10327,            // USB端口号未授权
    DF_TAX_ERR_CODE_USB_IO_HANDLE_ERROR = -10328,          // USB句柄失效
    DF_TAX_ERR_CODE_HOOK_SERVER_TIME_OUT = -10329,         //回调同步服务器超时
    //----NET层错误|税局错误-[2w,3w)
    ERR_TA_COMMON = -29999,
    ERR_TA_CLIENTHELLO,
    ERR_TA_AUTHCODE,
    ERR_TA_CONFIRM_LOGIN,
    ERR_TA_REPONSE_CHECK,
    ERR_TA_REPONSE_FAILE,
    ERR_TA_DZFPXML_PACKAGE,
    ERR_TA_GET_SERVERADDR,
    ERR_TA_DATA_ERROR,
    ERR_TA_PASSWORD_ERROR,
    ERR_TA_CERT_ERROR,           // 通讯证书异常
    ERR_TA_CERT_LOSS_REPORT,     // ERROR@98@证书已挂失
    ERR_TA_CERT_STATUS_UNKNOWN,  // ERROR@103@证书状态未知ph=-14202
    ERR_TA_CERT_BEEN_CANCELED,   // ERROR@97@证书已作废ph=-14204
    ERR_TA_HTTPS_INIT,
    ERR_TA_HTTPS_OPEN,
    ERR_TA_HTTPS_CLIENT_HELLO,
    ERR_TA_HTTPS_CLIENT_AUTH,
    ERR_TA_COMMUNITY_POST_ERROR,
    ERR_TA_UPLOAD_INVOICE,
    ERR_TA_UPLOAD_INVOICE_UPDATE,
    ERR_TA_UPLOAD_INVOICE_DOWNLOAD,
    ERR_TA_ETAX_LOGIN,
    ERR_TA_GET_JSONXML_VALUE,
    ERR_TA_TOKEN_CHECK,
    ErrorNET = -20000,  // 结束falg
    //------逻辑层错误|我方自定义错误-[10w,20w)
    ERR_LOGIC_COMMON = -100000,
    ERR_LOGIC_UPLOADINV_FAIL = -110000,
    ERR_LOGIC_UPLOADINV_BUILD_PREXML,
    ERR_LOGIC_UPLOADINV_RESULTCHECK,
    ERR_LOGIC_MONITOR_FAIL,
    ERR_LOGIC_MONITOR_TAXRATE,
    ERR_LOGIC_WASTETIME_OVERFLOW,
    ERR_LOGIC_CLEAR_LOCKED_INVOICE,
    ERR_LOGIC_CHECK_REPORT_TIME,
    ERR_LOGIC_REPORT_ERROR,
    ERR_LOGIC_NOTFOUND,
    ERR_LOGIC_DZFP_CANNOT_WASTE,
    ERR_LOGIC_UNSUPPORT_METHOD,
    ERR_LOGIC_NOTFOUND_INVOICETYPE,
    ERR_LOGIC_BUILD_FORMATBUF,  //构造各种格式化buf错误
    ERR_BUF_SIZE = -111000,
    ERR_BUF_ALLOC,
    ERR_BUF_OVERFLOW,
    ERR_BUF_CHECK,
    ERR_BUF_RESET,
    ERR_BUF_COPY,
    ERR_BUF_CONVERT,
    ERR_PARM_FORMAT = -112000,
    ERR_PARM_SIZE,
    ERR_PARM_FAIL,
    ERR_PARM_CHECK,
    ERR_PARM_NEEDMORE,
    ERR_PARM_INIT,
    ERR_PARM_PARSE,
    ERR_PARM_NULLPTR,
    ERR_IO_FAIL = -113000,
    ERR_IO_TIMEOUT,
    ERR_IO_REPCHECK,
    ERR_IO_BREAK,
    ERR_IO_FOPEN,
    ERR_IO_FREAD,
    ERR_IO_FWRITE,
    ERR_IO_FSTAT,
    ERR_IO_SOCKET_FAIL,
    ERR_IO_SOCKET_DUPLICATE,
    ERR_IO_INIT,
    ERR_DEVICE_NEEDUPDATE = -114000,  // EOS升级
    ERR_DEVICE_GET_TIME,
    ERR_DEVICE_GET_ENV,
    ERR_DEVICE_GET_CERT,
    ERR_DEVICE_CERT_CHECK,
    ERR_DEVICE_OPEN,
    ERR_DEVICE_LOAD_DEVICE,
    ERR_DEVICE_LOAD_ALL_PROPERTY,
    ERR_DEVICE_SELECTINV,
    ERR_DEVICE_PASSWORD_ERROR,  //设备密码错误
    ERR_DEVICE_PASSWORD_LOCK,   //设备密码锁定
    ERR_DEVICE_UNSUPPORT,
    ERR_DEVICE_GET_SIGNPARAMETER,
    ERR_DEVICE_COMMUNICATE,
    ERR_DEVICE_CURRENT_INVOICE,
    ERR_DEVICE_CLOSE,
    ERR_DEVICE_FIRMWARE_LOWVERSION,
    ERR_DEVICE_FIRMWARE_HIGHVERSION,
    ERR_DEVICE_NEEDUPDATE_CONFIG,  //小配置，密钥升级
    ERR_PROGRAME_UNSUPPORT = -115000,
    ERR_PROGRAME_NEED_UNLOCK,
    ERR_PROGRAME_API,
    ERR_PROGRAME_LOADDEV,
    ERR_CERT_PASSWORD_ERR = -116000,  //证书口令错误
    ErrorDev = -199999,               //结束falg
    //--USB层错误|设备厂商给出的标准错误[20w,~)
    // aisino,[20-21w]
    ERR_AISINO_COMMON = -210000,
    ERR_AISINO_QUERYTIME_LATER,
    ERR_AISINO_QUERYTIME_EARLY,
    ERR_AISINO_INVOICEVOLUME_TIME,
    ERR_AISINO_MAKEINVOICE_DATA,
    ERR_AISINO_MAKEINVOICE_MAX,
    ERR_AISINO_MAKEINVOICE_DEADLINE,
    ERR_AISINO_NO_DATA,
    ERR_AISINO_NO_STOCK,
    ERR_AISINO_NEED_REPORT,
    ERR_AISINO_UNKNOW,
    // nisec,[21-22w]
    ERR_NISEC_COMMON = -220000,
    ERR_NISEC_DEVICE,
    ERR_NISEC_PARAMENTER,
    ERR_NISEC_ILLEGAL_COMMAND,
    ERR_NISEC_OVERFLOW,
    ERR_NISEC_WRITE_PROTECT,
    ERR_NISEC_UNSUPPORT_INVOICETYPE,
    ERR_NISEC_DEADLINE_DATE,
    ERR_NISEC_DEADLINE_PRICE,
    ERR_NISEC_DEADLINE_COUNT,
    ERR_NISEC_DEADLINE_TIME,
    ERR_NISEC_DEVICE_NOTOPEN,
    ERR_NISEC_CERTPASSWORD_INCORRECT,
    ERR_NISEC_NO_DATA,
    ERR_NISEC_REPORT,
    ERR_NISEC_DEADLINE,
    ERR_NISEC_CANNOT_WASTE,
    ERR_NISEC_INCORRECT_FPDMHM,
    ERR_NISEC_INCORRECT_INPUT_DATE,
    ERR_NISEC_CLOCK_DAMAGE,
    // cntax,[22-23w]
    ERR_CNTAX_COMMON = -230000,
    // unknowDev
    ERR_UNKNOWDEV_COMMON = -240000,
    ErrorUSB = -999999,  // USB层错误|设备厂商给出的标准错误,tailFlag
};

#endif